### ISSUE TITLE
Sequence Pact Test Classes

### ISSUE THREAD

**Issue by kumarkrish85** [DiUS/pact-jvm#1117]
I am using Pact-JVM RestPactRunner and I have two contract pact files order.json and IRS.json , i want to execute order.json followed by IRS.json. But currently this run alphabetically (irs and order), I can keep the contents in one single JSON file but i want to keep it separately for each module of the project. My query is ,  is there way to consume the json file and call it's provider states? (or) how to control/define the order of pact file execution?

**Comment by mefellows** [comment]
This smells a bit to me like maybe Pact isn't being used appropriately here. Can I ask about your use case and why they must be called in sequence? One of the big things Pact solves is avoiding these kinds of order coupling.

Also, assuming the two contract files are for separate consumers?

**Comment by kumarkrish85** [comment]
We are trying to perform E2E testing. In that order service happens first followed by the IRS service

**Comment by mefellows** [comment]
OK I thought you might say that. Pact is not the tool for end-to-end testing, in fact, one of Pact's stated objectives is to _reduce_ or in some cases, completely remove the need for E2E testing.

Instead of doing end-to-end testing, we use contract tests to avoid the need to do that. Doing this has a lot of benefits, including the ability to test and release things separately, avoid the need for managing test environments, and reducing coupling/ordering.

Here are some links to help you understand what I mean a bit better:

- https://docs.pact.io/consumer/contract_tests_not_functional_tests
- https://docs.pact.io/faq/#do-i-still-need-end-to-end-tests
- https://docs.pact.io/getting_started/what_is_pact_good_for

**Comment by mefellows** [comment]
I should also suggest you run this workshop to understand all of the concepts: https://github.com/DiUS/pact-workshop-jvm

It takes about 1 hour, but is well worth your time so that you don't go too far down the wrong path.
