### ISSUE TITLE
`@Pact`: Remove definition of provider/consumer

### ISSUE THREAD

**Issue by C-Otto** [DiUS/pact-jvm#144]
As explained at the bottom of this comment: https://github.com/DiUS/pact-jvm/issues/75#issuecomment-65856715

**Comment by uglyog** [comment]
I think the opposite is required, remove the state from the @Pact annotation. Otherwise, how do you specify the consumer and provider?

**Comment by C-Otto** [comment]
I'd move the consumer/provider definitions to the `@PactRule` annotation, assuming one does not mix tests for different consumer/provider pairs in the same test class.

**Comment by uglyog** [comment]
#117 was raised to have two different providers, so it can't be added to the pact rule.

**Comment by C-Otto** [comment]
You cannot solve both issues, but you can decide on one. I obviously prefer mine.

**Comment by uglyog** [comment]
I'm optimistic that I can solve both issues :-) It may be a case of having two PactRules, one for a single provider and one where there is multiple.

**Comment by uglyog** [comment]
As a first step to solving these issues, I've deprecated the old rule and created a new one that is keyed on provider name. @Pact annotation drops the state, and the builder method is now responsible for setting the state. @PactVerification annotation now takes the provider name to use for the test method.

Have a look at https://github.com/DiUS/pact-jvm/blob/v2.x/pact-jvm-consumer-junit/src/test/java/au/com/dius/pact/consumer/pactproviderrule/PactProviderTest.java and let me know if this helps your issue.

**Comment by C-Otto** [comment]
I don't see the advantage of this. If you think about writing isolated tests, you only deal with one provider and one consumer. Repeating this in each `@Pact` is the original issue. Now you still demand the repetition, although spread out to other places.

In the code you referenced, you duplicated the `provider` information. I fail to understand why this is a good thing. What about having *all* tests and *all* pact definitions use the provider/consumer pair defined once (at the `PactRule`) instead?

Another thing, why is the `@PactVerification` annotation necessary? Can't you just let all `@Test` methods run against the mocked server? And what is the `expectMismatch` supposed to help with? Sorry, I'm confused here.

**Comment by uglyog** [comment]
This change was just to fix the conceptual problems with the original while still leaving the behavior the same. The author of the rule was probably assuming the consumer test could be mixed with non-pact tests, and I agree with this. I think that when providing frameworks we should not be prescriptive, but allow the users to use it however they wish.

However, I'm more than happy to add a more specialised implementation that has the behavior that your require, a single consumer and provider pair and each test method to execute in this context. I'll call it PactSingleProviderRule to make the intent clear. But this is essentially the same as ConsumerPactTest base test class.

Ignore the `expectMismatch` value on the  `@PactVerification` annotation. That is required to test failure conditions due to limitations with JUnit.

**Comment by uglyog** [comment]
I've enabled default behaviour with the pact rule so that the provider does not have to be repeated if there is only one. If no provider name is given, it will use the first one found. 

For an example, have a look at https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit%2Fsrc%2Ftest%2Fjava%2Fau%2Fcom%2Fdius%2Fpact%2Fconsumer%2Fpactproviderrule%2FPactProviderUsingDefaultsTest.java

**Comment by C-Otto** [comment]
Looks great!
