### ISSUE TITLE
pact-jvm-provider-junit not published to Maven Central

### ISSUE THREAD

**Issue by munk** [DiUS/pact-jvm#184]
http://mvnrepository.com/artifact/au.com.dius doesn't have the pact-jvm-provider-junit jar available. It seems like it should, as most of the other libraries are published there.

**Comment by uglyog** [comment]
It is not published automatically. It will be included in the next release, which I'll push out this weekend.

**Comment by uglyog** [comment]
Published

**Comment by GeorgeSimon** [comment]
When will pact-jvm-provider-junit 2.11 be published next? I'd like to try out Stephan's @PactUrl and @PactBroker.

**Comment by uglyog** [comment]
I'll push out a release this weekend

**Comment by GeorgeSimon** [comment]
Great, thanks! in the mean time, I'm trying to build pact-jvm locally. Not all projects are building. The only ones that are building are:
pact-jvm-provider-gradle
pact-jvm-provider
pact-jvm-model
pact-jvm-matchers

I made the following change to the build.gradle file in order to avoid trying to publish to sonatype.org:


changed lines 127-141 to:

    uploadArchives {
        repositories {
            mavenDeployer {
                beforeDeployment { def deployment -> signing.signPom(deployment) }
                mavenLocal()
            }
        }
    }

I'm new to gradle, but I do not think this change is what's preventing all of the projects to build. I'm using the following command:
gradle publishToMavenLocal

Any ideas? I'm most interested in the project pact-jvm-provider-junit.
Thanks

**Comment by uglyog** [comment]
If you just want to build it into your local maven repo, just run

gradle install

**Comment by GeorgeSimon** [comment]
Never mind. I ran gradle install and the projects built.
