### ISSUE TITLE
No feedback when using an invalid @Provider name in pact-jvm-provider-junit

### ISSUE THREAD

**Issue by stefan-lz** [DiUS/pact-jvm#188]
When using a @Provider with a provider name that does not exist, eg:

@RunWith(PactRunner.class)
@Provider("Provider Service WithTypo")
@PactFolder("xyz")
class PactTest {
..
..
}

No tests are run, and no error is reported and I get:

    Process finished with exit code 0

It's not finding any interactions to test, but I would expect an error or something.

**Comment by uglyog** [comment]
The other provider implementations display a warning when this is the case.

**Comment by uglyog** [comment]
Looking through the implementation, it will probably have to be an initialization error.

**Comment by stefan-lz** [comment]
Awesome - thanks for the quick fix.

**Comment by knok16** [comment]
Originally this piece of code was developed without such check intentionally because sometimes absence of pacts is legitimate situation. For example, we have a lot of microservices, use pact-broker, and code for running contract tests against provider are added when service is developed, and at this point of time service have not any consumer, i.e. have no any pacts in pact broker.

**Comment by stefan-lz** [comment]
@knok16, I raised this because the general idea is to not write any provider code until you have a pact from the consumer to test against it. I guess nothing is technically failing, so I'd be happy with a loud enough warning in the console too.
