### ISSUE TITLE
Make PactLoader annotation aware

### ISSUE THREAD

**Issue by lordofthejars** [DiUS/pact-jvm#230]
If you create a custom PactLoader, you need to provide by default a default constructor. This makes a bit complicated been able to pass parameters (basically you need to use env or prop variables). I think that we could make the system aware of this situation and allow the developers to define two possible constructors, one empty constructor and one where you can set an annotation.

Basically would imply modifying this line https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/main/java/au/com/dius/pact/provider/junit/PactRunner.java#L110 to make something like:

```
If pactSource.value() has a constructor with a parameter then
  if constructor has one parameter of same type of one annotation of test class
    instantiate using this constructor passing the annotation provided in the test class
  else
    fallback to default constructor
else
  instantiate using the empty constructor
```

So the tests would look like:

```
@PactSource(GitPactLoader.class)
@Git("https://.............")
```

And the GitPactLoader:

```
public class GitPactLoader {
  public GitPactLoader(Git git) {}
}
```

I can provide a PR with this implementation if you agree.

**Comment by uglyog** [comment]
Interesting idea. I can definitely see the benefit. The only problem is that it is a bit of magic behind the scenes, and has the potential to introduce some obscure errors for the user.

For example, how do you ensure that the appropriate annotation exists for the loader. What if the class types don't match up. In your example case, I assume it is an error to not have the `@Git` annotation, or to have an incorrect one? I don't know if the fall-back would work in this case. Does that mean if there is no annotation then there has to be some property values defined other wise it is an error?

Probably a good error message explaining what was missing and what the user needs to do is the solution. Maybe the solution needs to be to let the loader class initialise itself from the test class instead of the pact runner driving it.
 
So, maybe changing the PactRunner line to something like:

```java
            if (pactSource != null) {
                PactLoader pactLoader = pactSource.value().newInstance();
                pactLoader.initialiseFromTestClass(clazz);
                return pactLoader;
            } else {
```

would be better? Thoughts?

**Comment by lordofthejars** [comment]
Well it is another approach of course, but maybe it is easier for developer to remember in the constructor rather than having to remember a method name. But of course it is my opinion.

Or we can mix both approaches, which is:

```
public class GitPactLoader {
  public GitPactLoader() {
  }
}
```
Then default constructor is called.

But if you have:

```
public class GitPactLoader {
  public GitPactLoader(Class testClass) {}
}
```

Then the constructor passing the test class is used.

And in case of having:

```
public class GitPactLoader {
  public GitPactLoader(Class testClass) {}
  public GitPactLoader() {}
}
```

The one with the constructor is called. In this way there is no problem since all PactLoaders runs within a Test class. So it is up to the user to do something with the testClass or just ignore it.

Another option could be modifying the interface adding a new `init` method, but I discourage this solution since adds a break back compatibility.

WDYT?

**Comment by uglyog** [comment]
It's normally best to go with the simplest solution. Let's implement your initial idea. Do you want to create a PR?

**Comment by lordofthejars** [comment]
Yes I will do it, also thinking deeply I am going to implement passing the
test class, because what s happening if someone needs to use more than one
annotation, for example @GitCredentials and @Git.

Well you will receive a PR as soon as possible :)
