### ISSUE TITLE
XML body matching

### ISSUE THREAD

**Issue by hjoliveira** [DiUS/pact-jvm#243]
Hi there, 

Are there any examples for XML response body matching in consumer tests? [This](https://github.com/DiUS/pact-jvm/pull/125) pull request suggests this has been implemented, but it is not very clear to me how to do this.

Thanks!

**Comment by uglyog** [comment]
Nobody has provided any examples of XML body matching, and there is no DSL like for JSON bodies.

**Comment by andersthorbeck** [comment]
XML response matching would be very useful to me as well.
I attempted doing so with a regular expression approach, but it was very difficult to get right, and eventually failed because the [`DOTALL`](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#DOTALL) [embedded flag](https://docs.oracle.com/javase/tutorial/essential/regex/pattern.html) `(?s)` was marked in the javascript pact consumer as 
> SyntaxError: Invalid regular expression: `/(?s).*<rootElement xmlns="http://example\.com/ns/xml">.*/`: Invalid group

It seems to me, from the following tests
* https://github.com/DiUS/pact-jvm/blob/master/pact-specification-test/src/main/resources/v2/request/body/matches%20with%20regex%20xml.json, and
* https://github.com/DiUS/pact-jvm/blob/master/pact-specification-test/src/main/resources/v3/request/body/matches%20with%20regex%20with%20bracket%20notation%20xml.json
that XML response matching is now implemented for `pact-jvm`, and that these tests serve as some kind of documentation of required syntax.

My question is, is there any way to match XML which uses an explicit namespace and not just the default namespace? How can this be specified using the Pact Specification?

**Comment by uglyog** [comment]
XML matching is quite basic, and can not be applied based on namespaces. There is also no DSL like for JSON. You'll have to setup the matchers correctly, but it will work.

**Comment by mkinoo** [comment]
Hi, is there any update on an XML DSL for matching?

**Comment by uglyog** [comment]
@mkinoo We're added an initial version of XML support to Pact-JS with a DSL. Once we have some feedback from the community, that can be ported to Pact-JVM.

What testing framework and language would you use?

**Comment by mkinoo** [comment]
@uglyog thanks for the info! 
We'll be using junit5 & java.

**Comment by michielboekhoff** [comment]
Having tried the new XML DSL, I really like it! Thanks for implementing it so quickly.

One problem I have found is when omitting the namespace from the `PactXmlBuilder` - it throws an exception:

```
java.lang.IllegalStateException: doc.documentElement must not be null

	at au.com.dius.pact.consumer.xml.PactXmlBuilder.build(PactXmlBuilder.kt:45)
	at pacttests.consumer.butters.ButtersAddressLookupConsumerPactTest.createPact(ButtersAddressLookupConsumerPactTest.java:56)
	at au.com.dius.pact.consumer.junit.ConsumerPactTest.testPact(ConsumerPactTest.java:28)
```

Looking at the code in question, I suspect it's because when the namespace is omitted, `builder.newDocument()` is called, which returns an empty document (without the root element). The other branch - the one taken when the namespace is present - does the following:

```
DocumentImpl doc = new DocumentImpl(doctype);
Element e = doc.createElementNS( namespaceURI, qualifiedName);
doc.appendChild(e);
```
which seems to add the root element to the document.

The following code replicates this behaviour for me:

```java
new PactXmlBuilder("address").build(root -> {
    root.appendElement("organisationName", emptyMap(), organisationName -> 
        organisationName.setAttributes(singletonMap("name", "organisationName0")));
}
```

Furthermore, within this DSL, how would one add values to a tag as opposed to children?

**Comment by uglyog** [comment]
4.1.1 has been released with the fix

**Comment by mfbieber** [comment]
Hi,

I've had a look at the PactXmlBuilder - thanks for the updates on that!

Unfortunately, what we really need is a DSL that generates the matching rules for an XML response, as it is implemented for JSON. I belive this is also what other people commenting on this issue were looking for?

Could you reopen the issue and give an update on whether (and possibly when) you are planning to implement this?

Thanks a lot and best regards,
Michelle

**Comment by uglyog** [comment]
@mfbieber It does generate the matching rules. See https://github.com/DiUS/pact-jvm/blob/master/consumer/junit/src/test/java/au/com/dius/pact/consumer/junit/xml/TodoXmlTest.java

**Comment by mfbieber** [comment]
Oh yes, you are right of course. In the example I tested it didn't. Thanks for pointing to the other example, I think that might work for us!

Sorry for misunderstanding ;)

**Comment by shivkavitha** [comment]
Hi,

Do we have an example of PactXmlBuilder for apache kafka please ?

Many Thanks!

**Comment by uglyog** [comment]
@shivkavitha MessagePactBuilder already supports messages built with PactXmlBuilder

**Comment by shakul26** [comment]
is there a way to do only Schema Matchings  for xml response using PactXmlBuilder ?

i can see we can add matchers for attributes but it requires exact content to match to pass from provider side

**Comment by rholshausen** [comment]
No, that is no support for schema matching. There are lots of tools that would do that, and it makes no sense to make Pact another one.

**Comment by shakul26** [comment]
I later found we can still achieve same behaviour that is it can support schema testing as well.
