### ISSUE TITLE
Split Tests in multiple @Test methods

### ISSUE THREAD

**Issue by TheNitek** [DiUS/pact-jvm#244]
I'd like to use pact-jvm-consumer-junit_2.11 to test a few endpoints provided by one provider. The endpoints are not too complicated and for me it would make sense to create one PactFragement which covers them all.
Nevertheless I don't like the idea of having to test them all in the same @Test method or using the rather ugly pactFragment.runConsumer method. I thought setting "expectMismatch=true" would be ok to prevent pact from failing the tests, but now I realized this disables the generation of the pact files.

Therefore I'd like to request the ability to test one endpoint per @Test method (e.g. by generating the pact files even if expectMismatch is set to true)

**Comment by uglyog** [comment]
That is going to require a fair bit of refactoring to implement, as the current implementation validates the expectations for each test after each test has run. What you are asking for is a mechanism that runs all the tests, then validates all the expectations (i.e PactFragments) and then goes back and fails all the tests where the expectations where not met, in which case it is too late to get feedback related to an individual test run.

The `expectMismatch=true` is just for allowing tests to be written where the expectations are not all met. It is mainly for testing pact junit (similar to junit `@Test(expect=Exception)`). So the test will not fail, but because the expectations where not met, a contract will not be valid so no pact file is written.

We could add an `alwaysWritePact=true` value, which when used with the `expectMismatch=true` would achieve what you want, with the small problem being that your tests will always pass and a pact file written even when they are invalid. There will be no way to detect a valid failing test.

I would suggest defining multiple expectations, one that matches what the test is doing. Have a look at [PactProviderWithMultipleFragmentsTest.java](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-consumer-junit%2Fsrc%2Ftest%2Fjava%2Fau%2Fcom%2Fdius%2Fpact%2Fconsumer%2Fpactproviderrule%2FPactProviderWithMultipleFragmentsTest.java)

**Comment by uglyog** [comment]
Closing this as it is no longer relevant. JUnit 4 and 5 support in 4.0.x allows splitting tests into multiple test classes.
