### ISSUE TITLE
expectMismatch=true disables assertations

### ISSUE THREAD

**Issue by TheNitek** [DiUS/pact-jvm#245]
When using expectMismatch = true for a PactVerification, all asserts in this test case seem be ignored:

```
@Test
@PactVerification(expectMismatch = true)
public void testSomething() throws Exception {
   assertTrue(false);
}
```

results in a successful test. IMHO this is a bug and the pact annotations should not affect the junit behaviour.

**Comment by uglyog** [comment]
The `expectMismatch=true` is just for allowing tests to be written where the expectations are not all met. It is mainly for testing pact junit (similar to junit `@Test(expect=Exception)`). So the test will not fail, but because the expectations where not met, a contract will not be valid so no pact file is written.

I'll add a comment to this effect on the docs for the annotation.

**Comment by TheNitek** [comment]
I'm not sure I understand your explaination. I understood `expectMismatch = true` as something like "the pact part will fail, but that's ok". I don't see why this should affect asserts that are not at all related to pact at all. To me it looks like a `expectMismatch = true` can never fail, which makes it quite useless as test (compared to `@Test(expect=Exception)` which will fail if `Exception` is not thrown).

**Comment by uglyog** [comment]
Setting `expectMismatch = true` will invert the test result. The test will now pass if a mismatch occurs, and will fail if all the expectations are verified (no mismatch occurred), the test code throws an exception or a PactError is thrown.

**Comment by uglyog** [comment]
Sorry, just re-read your original comment with respect to the JUnit assertion failure. If that is happening then that is a bug.

**Comment by TheNitek** [comment]
You can just try the code example from my initial post. If you define a PactRule and execute this test it will pass even though the JUnit assertation should definitely fail.

**Comment by uglyog** [comment]
There is not much I can do about this, it is a limit of JUnit and exceptions in the JVM.

What is happening is that there are two failures happening, the `AssertionError` being raised from the test code and a `PactMismatch` because the test code made no requests to the mock server. The verification code can only allow one error through to the Pact Rule, and defaults to the `PactMismatch` over the `AssertionError`. With the `expectMismatch = true` it will then ignore the `PactMismatch` and the test passes (the `AssertionError` has been lost when the `PactMismatch` was detected).

I think this is important because any Pact tests should fail if the developer has accidentally commented out any code that makes the HTTP calls. This is probably the most likely scenario to occur, and it will also likely to generate an `AssertionError` because the test code will not get the responses it expects. In this case, I want to get a `PactMismatch` failure over a "expected status 200 but got null".

I'm going to deprecate the `expectMismatch` value and remove it in a future version.
