### ISSUE TITLE
Issues when URL contains encoded string

### ISSUE THREAD

**Issue by nikhilkr123** [DiUS/pact-jvm#339]
My URL is like this _/tenants/**tester%2Ftoken**/jobs/external-id_ 
But when pact provider verifies this, its sending following request to server and resulting 404 _/tenants/**tester/token**/jobs/external-id_ 

I am using following version of pact jvm 
au.com.dius:pact-jvm-provider-junit_2.11:3.3.1
PactSpecVersion.V3

**Comment by uglyog** [comment]
Wow, that was always going to cause problems ;-)

I have re-opened the original issue #66. But there is no way for me to automatically handle this case, because I have to decode the path and query strings from the pact file to protect against double encoding from the HTTP client.

The best I can do is put in a flag so you can get pact to not decode the path, but you will have to ensure your query strings are not encoded in the pact file, otherwise they will be double encoded by the HTTP client.

**Comment by nikhilkr123** [comment]
Thats works for me. I can make sure query strings are not encoded.

**Comment by uglyog** [comment]
Adding a switch to not decode your URL will not help you. Apache HTTP Client encodes the paths, so your URL will end up being double encoded (/tenants/tester%252Ftoken/jobs/external-id).

**Comment by nikhilkr123** [comment]
The URLs in my pact files are not double encoded.
`/tenants/tester%2FapplicationId:token/jobs/external-id/job_id_3"`
So I don't think it will be a problem.

**Comment by uglyog** [comment]
I did not mean the URL in the pact file. What will happen is when the request is made to the provider, the percentage will be encoded to `%25` by the HTTP client, so the path in the pact file will be converted from

 /tenants/tester**%2F**token/jobs/external-id
                           
to

/tenants/tester**%252F**token/jobs/external-id

**Comment by nikhilkr123** [comment]
@uglyog The double encoding is not done by the HttpClient. Its happening when we create URL using [URIBuilder](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider/src/main/groovy/au/com/dius/pact/provider/ProviderClient.groovy#L225).

This can be avoided if we use the following parameter constructor of _URIBuilder (String uri)_.

I have created a fix for it, please take a look at this [commit](https://github.com/nikhilkr123/pact-jvm/commit/e18a46a703da1071e6332d98c173039dd762dad0) I am not familiar with this code base, so I have provided a system property to disable the decoding.

**Comment by uglyog** [comment]
That looks ok, I might just rename the JVM property to be specific to the pact library.

**Comment by uglyog** [comment]
Turns out it was not as simple as that. The reason I was using URIBuilder was to guard against paths that are not correctly encoded. _URIBuilder(String uri)_ will throw an exception if the path is not correctly encoded (for instance there is a space).

I've set the override property to `pact.verifier.disableUrlPathDecoding`. Hopefully, this should now work for your case.

**Comment by nikhilkr123** [comment]
Could you please release a version with these changes, so that I can use it in my project.

**Comment by uglyog** [comment]
Version 3.3.3 released

**Comment by nikhilkr123** [comment]
@uglyog Do we need to do something for the Consumer side? I have seen PACT Consumer decode the URL once. Any thoughts?

**Comment by uglyog** [comment]
I would be hesitant to change the behaviour of the consumer side code unless it is causing a problem.

**Comment by nikhilkr123** [comment]
Sorry, I am already facing the trouble. 
`/tenants/tester%2FapplicationId:token/jobs/external-id/job_id_3` is becoming `/tenants/tester/applicationId:token/jobs/external-id/job_id_3` unless i double encode that segment.

**Comment by luch1111** [comment]
Hi, was this issue fixed? I am using pact-jvm-provider-junit_2.12  <version>3.5.10 and facing this problem

**Comment by uglyog** [comment]
@luch1111 can you try with the latest version?

**Comment by luch1111** [comment]
@uglyog , latest version works fine, thanks!
