### ISSUE TITLE
Pact JVM JUnit Provider doesn't fail when States are missing

### ISSUE THREAD

**Issue by cah-andrewfitzgerald** [DiUS/pact-jvm#345]
When tests are run that require a provider state using the JUnit provider, the test proceeds without setting a state if a state annotation is not found.

The test should instead fail with an error message informing the user that there is no annotation containing the given provider state.

**Comment by uglyog** [comment]
The tests will now fail with something similar to the following error:

    MissingStateChangeMethod: Did not find a test class method annotated with @State("SomeProviderState")

**Comment by nikhilkr123** [comment]
In my PACT, there are 8 interactions. But at provider I am changing the state of two interactions. Those two tests passes, but remaining 6 failed with following error.

`MissingStateChangeMethod: Did not find a test class method annotated with @State`

I am using 3.3.3 and this was working with 3.3.1

**Comment by uglyog** [comment]
This is now the default behaviour. You need to define a state change method for all the required states.

**Comment by nikhilkr123** [comment]
It will make the tests with empty @State method. 
I think thats not right ! It would be nice if we keep the state change at provider as optional.

**Comment by uglyog** [comment]
The problem is if someone forgets to add a state change, the test may fail in some obscure way and make take a while to diagnose. This change forces you to consider all the state changes that are defined in the pact file.

I agree that it may lead  some empty methods, but I feel in this case it is worth it. This brings it in line with the behaviour from the Ruby version.

If there is a lot of empty state change methods, it might be better to discuss removing those from the consumer tests.

**Comment by cah-andrewfitzgerald** [comment]
This is good to close on my end... thanks again @uglyog!
