### ISSUE TITLE
pact-jvm-provider-junit messaging tests fail when run via maven

### ISSUE THREAD

**Issue by Fitzoh** [DiUS/pact-jvm#382]
See this repo for an example: https://github.com/Fitzoh/pact-jvm-maven-test-issue

If you clone the project and run `ProviderMessageTest`through intellij, it will pass.

However, it run run the tests via maven (`mvn test`) it fails with the following message:
```

Verifying a pact between consumer and provider
  a test message
      Verification Failed - No annotated methods were found for interaction 'a test message'

Failures:

0) a test message
      No annotated methods were found for interaction 'a test message'

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.946 sec <<< FAILURE!
consumer - a test message(com.example.ProviderMessageTest)  Time elapsed: 0.327 sec  <<< FAILURE!
java.lang.AssertionError: 
0 - No annotated methods were found for interaction 'a test message'
        at au.com.dius.pact.provider.junit.target.BaseTarget.getAssertionError(BaseTarget.java:84)
        at au.com.dius.pact.provider.junit.target.AmqpTarget.testInteraction(AmqpTarget.java:51)
        at au.com.dius.pact.provider.junit.InteractionRunner$2.evaluate(InteractionRunner.java:181)
        at au.com.dius.pact.provider.junit.InteractionRunner.run(InteractionRunner.java:141)
        at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:101)
        at au.com.dius.pact.provider.junit.PactRunner.runChild(PactRunner.java:51)
```

**Comment by uglyog** [comment]
This is a classpath issue when run from maven. I see if I can work out what is happening.

**Comment by zwant** [comment]
I'm hitting this very same issue. Works fine from IntelliJ but not through maven. It mentions "org.reflections.Reflections - Reflections took 6 ms to scan 1 urls, producing 0 keys and 0 values"
which seems wrong...

**Comment by zwant** [comment]
I think I found the issue. The failsafe runner was trying to run my producer tests, and since it at that point does not know about pact, it fails.

To work around it, I added my producer tests as excluded by failsafe, and I added the "pact-jvm-provider-maven" plugin to the "verify" lifecycle phase.

Now, failsafe will first run my consumer tests and then afterwards the "pact:verify" target will run to verify the producer.

Since I'm doing a proof-of-concept I have both producer and consumer in the same repo which creates this messy situation.

So for anyone running into this problem with producer tests, see if it's actually surefire (or similar) picking up and trying to run the tests, instead of the pact-maven plugin.

**Comment by RaghuJ** [comment]
Any update on this issue. I'm facing the same issue.

**Comment by uglyog** [comment]
@RaghuJ check that you are not running the verification as a test. It should be run by the pact-maven plugin and not a unit test.

**Comment by RaghuJ** [comment]
@uglyog Thanks :) I was able to run it.

**Comment by Semirhage** [comment]
I was able to run the test with the failsafe maven plugin, by adding the following config to the plugin:
```
 <configuration>
      <useManifestOnlyJar>false</useManifestOnlyJar>                                 
</configuration>
```

The test failed when being run with the **failsafe**  (or **surefire**) maven plugins, because the  SystemClassLoader returned only the failsafe/surefire booter.jar, when the classpath urls were being retrieved from it (check code in [AmqpTarget.java](https://github.com/DiUS/pact-jvm/blob/master/pact-jvm-provider-junit/src/main/java/au/com/dius/pact/provider/junit/target/AmqpTarget.java#L92) ).

With the configuration in place, the full classpath is being listed through the SystemClassLoader, and therefore the `@PactVerifyProvider` annotations are correctly identified. 

For more plugin configuration details, check  [Failsafe Class Loading](http://maven.apache.org/surefire/maven-failsafe-plugin/examples/class-loading.html)
