### ISSUE TITLE
Gradle plugin 3.0.2 can not publish pact file

### ISSUE THREAD

**Issue by wldandan** [DiUS/pact-jvm#407]
I was using the following gradle plugin to publish the pact file.
`classpath 'au.com.dius:pact-jvm-provider-gradle_2.11:3.0.2'`

but I always got the result is 

> 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pactPublish'.
groovyx.net.http.HttpResponseException: Bad Request

---
if I used rake task `be rake pact:publish`, it works fine
Not sure what is going wrong?  do you have any suggestions?

**Comment by uglyog** [comment]
"bad request" is the response when the pact broker has rejected the pact file. This is normally due to the provider name being similar to another one in the repository, but if the ruby version is working it may be something else.

If you run the publish task with debug level logging, you should see more information. Also, try the latest version (3.3.8).

**Comment by bbarke** [comment]
I just ran into this issue. I had to change my gradle version from 1.0-SNAPSHOT to 1.0 and it worked

**Comment by uglyog** [comment]
"No signature of method" issue has been raised by others, and I have a fix in place for it.
