### ISSUE TITLE
Publish pact verification

### ISSUE THREAD

**Issue by uglyog** [DiUS/pact-jvm#417]
As per https://github.com/bethesque/pact_broker/blob/verifications/lib/pact_broker/doc/views/publish-verification-results.markdown

This is required in all the verification modules.

**Comment by bethesque** [comment]
From the ruby wiki:

## Publishing verification results to a pact broker

If you are using version 1.11.0 or later of the pact gem and 2.0.0 or later of the pact broker, you can automatically publish the results of pact verifications back to the broker by setting the `app_version` and `publish_verifications` options in your service provider configuration. The recommended way to do this so that you only publish verifications from your CI is:

```ruby
build_number = ENV.fetch('BUILD_NUMBER','alpha')
publish = !!ENV['BUILD_NUMBER']

Pact.service_provider "My Service Provider" do
  app_version "1.3.#{build_number}"
  publish_verifications publish
end

```

If your pact URL includes basic auth configurations for the pact broker, these will be used to publish the verification.

**Comment by uglyog** [comment]
Released 4.5.4 with publishing verification results

**Comment by bethesque** [comment]
👍

**Comment by bethesque** [comment]
Documentation updated: https://github.com/pact-foundation/pact_broker/wiki/Provider-verification-results#publishing
