### ISSUE TITLE
Message metadata verification on provider side

### ISSUE THREAD

**Issue by andreschaffer** [DiUS/pact-jvm#479]
Hi there! 

This would be a feature request:
Verify also the metadata for message pacts on the provider side.
Currently it is possible to specify metadata for message pacts on the consumer side, but the corresponding verification on the provider side is missing.

**Comment by uglyog** [comment]
What would you like to do with the metadata on the provider side?

**Comment by andreschaffer** [comment]
I would like to be able to verify that the provider provides a message with both contents and metadata as expected by consumers. 
Or was your question more towards specific use cases?

**Comment by uglyog** [comment]
No, that makes sense. Will require a bit of a refactor to include any metadata.

**Comment by andreschaffer** [comment]
👍

**Comment by muralikrishna8** [comment]
any update on this one?

**Comment by uglyog** [comment]
I haven't had the opportunity to work on this yet.

**Comment by dbubenheim** [comment]
Hi everyone. Our use case is the following:

Basically we have a messaging contract between a provider and a consumer and we would like to share some meta-information which are not part of the actual message payload, such as the topic name, content-type etc. 

Is there any chance to get this feature in one of the upcoming releases? Or do you have an alternative approach to share those information mentioned above?

**Comment by cstettler** [comment]
Hi @uglyog, is there any plan to support matching on metadata in the near future? That would be a very valuable enhancement for contract testing for message providers. 

I think it would be great to be able to return some kind of message abstraction (with payload and metadata) from the `@PactVerifyProvider`-annotated methods (instead of just a plain `String`) and perform the comparison on that message abstraction. 

Also, I think it would be good not to rely on the `contentType` metadata by default, as not every use case has exactly this metadata set. Maybe an explicit property on that message abstraction would be better, in case it is required for the comparison of the body.

**Comment by uglyog** [comment]
This is currently in progress. I have started with the consumer side DSLs to allow matchers to be specified for the metadata. I haven't gotten around to the provider side as yet. You are correct in that the provider methods would have to return both the message contents and metadata to be compared.

**Comment by uglyog** [comment]
Version 3.6.5 has been released with this feature

**Comment by gayatreemishra** [comment]
Hi @uglyog, is metadata comparison available for java application as well?

**Comment by uglyog** [comment]
> Hi @uglyog, is metadata comparison available for java application as well?

@gayatreemishra it's for all JVM applications
