### ISSUE TITLE
Ability to point maven-plugin to a directory of pacts for verification

### ISSUE THREAD

**Issue by mortenlj** [DiUS/pact-jvm#79]
A pact-file contains both provider and consumer names, so instead of having to configure each provider and each consumer individually, it should be possible to point to a directory and say "do all of those".

Or at least a possibility to define a provider, and say "do all of those that match this providers name".

(By the way, awesome timing with the pact-jvm-provider-maven release, as I was going to start using it today :-))

**Comment by uglyog** [comment]
Damn, you caught me out ;-) I decided to leave that out for the first release.

The maven plugin just wraps the gradle plugin, and the gradle plugin already supports that so it just a matter of implementing the correct config.

**Comment by uglyog** [comment]
The gradle plugin still requires you to define the providers, because there is additional config not in the pact files (like hostname and port, etc.). I'm thinking to do the same. So you can define a path to a directory for a provider, and it will load all the pact files that match the provider name.

**Comment by mortenlj** [comment]
This looks great! I'll test it out on monday (if not sooner), but it looks like it's just what I need.

**Comment by uglyog** [comment]
I haven't tested it as yet. I'll also give it a run through monday.

**Comment by mortenlj** [comment]
I've tested this now, and it works fine. Thanks!
